### ISSUE TITLE
Can someone tell me the significance of the hidden folder with underscore.ie. in the example what is the requirement of _mypkg??

### ISSUE THREAD

**Issue by megumi123** [pytest-dev/apipkg#11]

**Comment by RonnyPfannschmidt** [comment]
its simply the pattern in python for "private" objects

**Comment by megumi123** [comment]
But will it make a difference or will it affect anything if we create modules and write apipkg in the same package??

**Comment by megumi123** [comment]
i am asking it there will be problems if we skip the _mypkg creation

**Comment by RonnyPfannschmidt** [comment]
@megumi123 i dont think so - its simply a  pattern that helps you separate things sanely

**Comment by RonnyPfannschmidt** [comment]
@megumi123 things you consider private from things you want to publish

**Comment by megumi123** [comment]
Thanks a lot for all our help and quick replies
