### ISSUE TITLE
2.1.0 broken on Python 3.4

### ISSUE THREAD

**Issue by avylove** [pytest-dev/apipkg#29]
2.1.0 seems to be broken on Python 3.4

```
  File "/home/runner/work/blessed/blessed/.tox/py34/lib/python3.4/site-packages/apipkg/__init__.py", line 69, in initpkg
    mod = _initpkg_py3(mod, pkgname, exportdefs, attr=attr)
  File "/home/runner/work/blessed/blessed/.tox/py34/lib/python3.4/site-packages/apipkg/__init__.py", line 141, in _initpkg_py3
    mod.__class__ = ApiModule
TypeError: __class__ assignment: only for heap types
```

For my purposes I can probably pin to 2.0.1. However, the readme for this package specifically calls out support fr 3.4+, but I notice 3.4 is not being tested. 3.4 can be tested in GH actions by pinning `os:  ubuntu-18.04`. Please fix or drop support for 3.4.

**Comment by webknjaz** [comment]
Looks like @RonnyPfannschmidt removed 3.4 from the matrix here: https://github.com/pytest-dev/apipkg/pull/24/files#diff-cbf97851bdfebccf2fcdd8848c6a93adb8d8affd5c6b1faf00238d528c3ef6cbR41.

**Comment by webknjaz** [comment]
The actual change that broke the support for Python 3.4: https://github.com/pytest-dev/apipkg/pull/27/files#diff-4bc719ceb16107716536f677236ec1d9038a2f419bea6fec8a5773dd6e2ca684R141.

**Comment by webknjaz** [comment]
@RonnyPfannschmidt if it's not desired to keep the support for Python 3.4, `python_requires` needs to be updated and the previous release yanked. If it's an unintended bug — maybe it could be fixed?

cc @GlenWalker

**Comment by RonnyPfannschmidt** [comment]
Unintended, im not sure when I can get to fixing

**Comment by webknjaz** [comment]
@RonnyPfannschmidt maybe you could still update the metadata, republish a new patch release for `>=3.5`, and yank the broken one? As a damage control measure. Then #31 could re-enable 3.4 and lower `python_requires` back to what it was.

**Comment by RonnyPfannschmidt** [comment]
yanked after a 2.1.1 with patch

the next release will drop support for all dead python versions
