### ISSUE TITLE
test_get_distribution_version is broken with pytest 7.2 and tox 4

### ISSUE THREAD

**Issue by frenzymadness** [pytest-dev/apipkg#43]
This assert

https://github.com/pytest-dev/apipkg/blob/70a9a036bdefad85ffa628315c4e134199eb5f00/test_apipkg.py#L835

counts that py will always be installed but pytest 7.2 and tox 4 no longer depend on py so it might not be available which makes this test to fail.

**Comment by mgorny** [comment]
Making assertion on `setuptools` also doesn't sound future-proof for a PEP517 world where build requirements are only installed in a temporary venv.
