### ISSUE TITLE
fails when start pytest 3.11.5

### ISSUE THREAD

**Issue by vdkmvx** [pytest-dev/apipkg#48]
sup, when i start "pytest" got this error

> 22:36:51  + pytest
22:36:51  Traceback (most recent call last):
22:36:51    File "/usr/lib/python3.11/site-packages/py/_vendored_packages/apipkg.py", line 141, in __makeattr
22:36:51      modpath, attrname = self.__map__[name]
22:36:51                          ~~~~~~~~~~~~^^^^^^
22:36:51  KeyError: '__spec__'
22:36:51  
22:36:51  During handling of the above exception, another exception occurred:
22:36:51  
22:36:51  Traceback (most recent call last):
22:36:51    File "/usr/bin/pytest", line 5, in <module>
22:36:51      from pytest import console_main
22:36:51    File "/usr/lib/python3.11/site-packages/pytest/__init__.py", line 5, in <module>
22:36:51      from _pytest._code import ExceptionInfo
22:36:51    File "/usr/lib/python3.11/site-packages/_pytest/_code/__init__.py", line 2, in <module>
22:36:51      from .code import Code
22:36:51    File "/usr/lib/python3.11/site-packages/_pytest/_code/code.py", line 42, in <module>
22:36:51      from _pytest._io import TerminalWriter
22:36:51    File "/usr/lib/python3.11/site-packages/_pytest/_io/__init__.py", line 1, in <module>
22:36:51      from .terminalwriter import get_terminal_width
22:36:51    File "/usr/lib/python3.11/site-packages/_pytest/_io/terminalwriter.py", line 10, in <module>
22:36:51      from _pytest.compat import final
22:36:51    File "/usr/lib/python3.11/site-packages/_pytest/compat.py", line 44, in <module>
22:36:51      LEGACY_PATH = py.path. local
22:36:51                    ^^^^^^^^^^^^^^
22:36:51    File "/usr/lib/python3.11/site-packages/py/_vendored_packages/apipkg.py", line 148, in __makeattr
22:36:51      result = importobj(modpath, attrname)
22:36:51               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:36:51    File "/usr/lib/python3.11/site-packages/py/_vendored_packages/apipkg.py", line 69, in importobj
22:36:51      module = __import__(modpath, None, None, ['__doc__'])
22:36:51               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
22:36:51    File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
22:36:51    File "<frozen importlib._bootstrap>", line 1136, in _find_and_load_unlocked
22:36:51    File "/usr/lib/python3.11/site-packages/py/_vendored_packages/apipkg.py", line 146, in __makeattr
22:36:51      raise AttributeError(name)
22:36:51  AttributeError: __spec__

**Comment by RonnyPfannschmidt** [comment]
this is a issue with pylib being outdated, not apipkg itself anymore

**Comment by RonnyPfannschmidt** [comment]
closing as dup of #33

**Comment by vdkmvx** [comment]
what should i do?

**Comment by levrik** [comment]
I'm hit by the same issue after upgrading to Python 3.11. The error comes from inside the Python distribution so I'm also a bit lost on what to do.

**Comment by levrik** [comment]
Upgrading `pytest` from 7.x to 8.x helped in the end as well. I was going back to a rather old project TBH which was started on Python 3.8.
